name: jedo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  flutter_typeahead: ^5.2.0
  http: ^1.3.0
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/user.png
  - assets/moto.jpg
  - assets/moto.png
  - assets/logo.jpeg
  - assets/logo.png
  - assets/origem.png
  - assets/destino.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"
